Show databases;

Create database customer_behavior;
SELECT * FROM customer limit 5;

-- What is the total revenue generated by male vs female customers?
SELECT gender,SUM(purchase_amount) as revenue FROM customer
GROUP BY gender;

-- Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id , purchase_amount FROM customer
WHERE discount_applied = 'Yes' and purchase_amount >= (SELECT AVG(purchase_amount) FROM customer);

-- Which are the top 5 products with the hightest average review rating?
SELECT item_purchased , ROUND(AVG(review_rating),2) AS "Average Product Rating" FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- Compare the average Purchase Amounts between Standard and Express Shipping?
SELECT shipping_type , ROUND(AVG(purchase_amount),2) AS rounded FROM customer
WHERE shipping_type in ('Standard','Express') 
GROUP BY shipping_type;

-- Do Subscribed customers spend more? Compare average Spend and total revenue between subscribers  and non-subscribers?
SELECT subscription_status , COUNT(customer_id) AS Total_customers,
ROUND(AVG(purchase_amount),2) AS "Avg_spend",ROUND(SUM(purchase_amount),2) AS "Total_revenue"
FROM customer
GROUP BY subscription_status
ORDER BY Total_revenue, Avg_spend DESC;


-- Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased ,
ROUND(100* SUM(CASE WHEN discount_applied = "Yes" THEN 1 ELSE 0 END)/COUNT(*) ,2) AS discount_rate FROM customer 
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Segment customers into New ,Returning and Loyal  based on their total no.of previous purchases and show the count of 
-- each segment?
WITH customer_type As (
SELECT customer_id, previous_purchases,
CASE
   WHEN previous_purchases= 1 THEN 'NEW'
   WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
   ELSE 'Loyal'
   END AS customer_segment
FROM customer
)

SELECT customer_segment , COUNT(*) AS "Number of customers" FROM customer_type
GROUP BY customer_segment;

-- What are the top 3 most purchased products within each category?
	WITH item_counts AS (
    SELECT category , item_purchased, COUNT(customer_id) As total_orders,
    ROW_NUMBER()  over(partition BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
    )
    
    SELECT item_rank ,category ,item_purchased ,total_orders FROM item_counts
    WHERE item_rank <=3;

_-- Are customers who are repeat buyers(more than 5 purchases) also likely to subscribe?
SELECT subscription_status, COUNT(customer_id) AS repeat_buyers FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status ;

-- What is the revenue contribution of each age group ?
SElect age_group, SUM(purchase_amount) AS total_revenue FROM customer
GROUP BY  age_group 
ORDER BY total_revenue DESC;

